TMP_DIRECTORY="/tmp/"
WEATHER_OPENWEATHERMAP_API_KEY="paste your openweathermap.org API key here"
NETWORK_INTERFACE="wlp7s0"
NETWORK_DISPLAY_PUBLIC_IP="true"
NETWORK_PUBLIC_IP_LOOKUP_URL="https://api.ipify.org/"
